### ISSUE TITLE
Flash CM4 modules

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-Firmware#22]
**Parent epic #23**

# Description
_As a user, I want a simple way to flash a CM4 module from my bmc so I'm not bothered with executing several manual steps._

The aim is to extend the tpi and bmc application with functionality to flash cm4 modules, implementing the `tpi --flash` command. Which is currently still flagged as a to-do.
 

Not in scope are the following tasks:
- Flash multiple modules at once
- #28
- #29 
- #30 

# Tasks
- [x] enable usbboot package in buildroot
- [x] Create middleware for the USB and Power switching
- [x] Create middleware to put the rpiboot pin high
- [x] Create middleware to call usbboot routines
- [x] implement business logic
- [x] extend the CLI application to handle this new interface
 

# Acceptance Criteria

* The user can successfully flash a given image from the internal sdcard to one of the modules 
* The user gets reported on the progress during the process
* the integrity of the flashed image is verified at the end of writing the image
* Required middleware is rewritten in rust
