### ISSUE TITLE
Flash RK1 modules

### ISSUE THREAD

**Issue by svenrademakers** [turing-machines/BMC-Firmware#45]
**Parent epic #23**

# Description
_As a user, I want a simple way to flash a RK1 module from my bmc so I'm not bothered with executing several manual steps._
 

# Tasks
- [x] POC: execute steps manually.
- [x] Update middleware
- [x] update business logic
- [x] extend the CLI application so that the user can specify which module type is going to be flashed
 

# Acceptance Criteria

* The user can successfully flash a given image from the internal sdcard to one of the RK1 modules 
* The user gets reported on the progress during the process
* the integrity of the flashed image is verified at the end of writing the image

**Comment by svenrademakers** [comment]
fixed with commit https://github.com/turing-machines/bmcd/commit/18e3e8e574f90e6b3c340b62811d0392b2413a17
